dist: xenial
language: ruby
rvm: 2.5.3
gemfile:
  - Gemfile
  - test/gemfiles/actionmailer51.gemfile
  - test/gemfiles/actionmailer50.gemfile
  - test/gemfiles/actionmailer42.gemfile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
