dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/rails52.gemfile
  - test/gemfiles/rails51.gemfile
  - test/gemfiles/rails50.gemfile
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
